FROM openjdk

COPY massive-imprinter-0.1-RC1-SNAPSHOT-jar-with-dependencies.jar .
# COPY config.properties .

EXPOSE 9998

ENTRYPOINT java -jar massive-imprinter-0.1-RC1-SNAPSHOT-jar-with-dependencies.jar config.properties
