FROM debian:8.8

RUN apt-get update
RUN apt-get install -y build-essential
RUN apt-get install -y libcurl4-openssl-dev
RUN apt-get install -y cmake
RUN apt-get install -y libssl-dev

WORKDIR /
COPY ./tank-c /tank-c
WORKDIR /tank-c
RUN make

WORKDIR /tank-c/bin
# COPY tank-c.ini .

ENTRYPOINT ./tank-c
