FROM nginx:latest
RUN ["mkdir", "/html"]
COPY ["./start.sh", "."]
COPY ["./dashboard.conf", "/etc/nginx/conf.d/default.conf"]
COPY ["./build", "/html"]
# COPY ["./conf.json", "/html/conf.json"]
ENTRYPOINT ./start.sh
EXPOSE 8081
