FROM node:8

RUN wget https://bitcoin.org/bin/bitcoin-core-0.15.0.1/bitcoin-0.15.0.1-x86_64-linux-gnu.tar.gz
RUN tar xzf bitcoin-0.15.0.1-x86_64-linux-gnu.tar.gz
RUN install -m 0755 -o root -g root -t /usr/local/bin bitcoin-0.15.0/bin/*
COPY package.json .
RUN npm install
COPY index.js .

ENTRYPOINT npm start
