version: "3.3"

services:
  mqtt:
    build: ../mqtt
    image: uniquid/dev-mqtt
    volumes:
      - ${MQTT_CONFIG_1}:/etc/rabbitmq/rabbitmq.conf
    ports:
      - 1883:1883
      - 1884:1884
      - 4369:4369
      - 5671:5671
      - 5672:5672
      - 15671:15671
      - 15672:15672
      - 25672:25672

    networks:
      default:
        ipv4_address: 172.18.0.3

  registry:
    build: ../registry
    image: uniquid/dev-registry
    volumes:
      - ${REGISTRY_CONFIG}:/config.properties
    ports:
      - 8080:8080
    networks:
      default:
        ipv4_address: 172.18.0.5

  imprinter:
    build: ../imprinter
    image: uniquid/dev-imprinter
    volumes:
      - ${IMPRINTER_CONFIG}:/config.properties
    env_file: .env
    ports:
      - 9998:9998
    networks:
      default:
        ipv4_address: 172.18.0.6
    links:
      - mqtt
      - registry

  orchestrator:
    build: ../orchestrator
    image: uniquid/dev-orchestrator
    volumes:
      - ${ORCHESTRATOR_CONFIG}:/config.properties
    env_file: .env
    environment:
      - LOCAL_IP=$LOCAL_IP
    ports:
      - 9999:9999
    networks:
      default:
        ipv4_address: 172.18.0.8

networks:
  default:
    ipam:
      config:
        - subnet: 172.18.0.0/16
